In [2]:
# swarm = [Particle() ...]
# while not stop():
#     for particle in swarm:
#         r_l, r_g ~ U(0, 1)
#         izracunaj novu brzinu v = inercija + lokalno + globalno
#         izracunaj novu poziciju p = p + v  

In [137]:
import random
import numpy as np

In [143]:
num_dimensions = 2
bounds = np.array([[-5.12, 5.12] for _ in range(num_dimensions)])

In [144]:
lower_bounds = bounds[:,0]
lower_bounds

array([-5.12, -5.12])

In [145]:
def rastrigin(x):
    A = 10
    n = len(x)
    return A*n + sum(x[i]**2 - A*np.cos(2*np.pi*x[i]) for i in range(n))

In [131]:
# # Jedna cestica u roju. Svaka cestica ima poziciju i brzinu u nekom domenu i
# # prati najbolju poziciju (svoju) i najbolju poziciju celog roja

# class Particle:
#     swarm_best_position = None
#     swarm_best_value = None
    
#     def __init__(self, bounds, f, c_i, c_p, c_s):
        
#         # koeficijent inercije - tendencija za kretanjem u trenutnom smeru
#         self.c_i = c_i
#         # kognitivni koeficijent - tendencija da se krece ka svojoj najboljoj poziciji 
#         self.c_p = c_p
#         # socijalni koeficijent - tendencija da se krece ka globalnoj najboljoj poziciji
#         self.c_s = c_s
        
#         # bounds - gornje i donje granice 
#         self.lower_bounds = bounds[:, 0]
#         self.upper_bounds = bounds[:, 1]
        
#         # pozicija i brzina ([a, b] format) 
#         self.position = np.random.uniform(self.lower_bounds, self.upper_bounds, len(bounds))
#         self.velocity = np.random.uniform(-1, 1, len(bounds))
        
#         # pratimo najbolju poziciju i vrednost funkcije za tu poziciju
#         self.personal_best_position = self.position
        
#         self.f = f
#         self.value = f(self.position)
#         self.personal_best_value = self.value
        
#         # inicijalizujemo globalne promenljive
#         if Particle.swarm_best_value is None or Particle.swarm_best_value > self.value:
#             Particle.swarm_best_position = self.position.copy()
#             Particle.swarm_best_value = self.value
    
#     def update_position(self):
#         # clip da bi bilo u rasponu lower i upper bounda
#         # p = p+v
#         self.position = np.clip(self.position + self.velocity,
#                                    self.lower_bounds,
#                                    self.upper_bounds)
#         self.value = self.f(self.position)
            
#         # updateujemo personal best i swarm best
#         if self.value < self.personal_best_value:
#             self.personal_best_value = self.value
#             self.personal_best_position = self.position.copy()
                
#             if self.value < Particle.swarm_best_value:
#                 Particle.swarm_best_position = self.position.copy()
#                 Particle.swarm_best_value = self.value
        
#     def update_velocity(self):
#         # vektor od trenutne do licne najbolje pozicije
#         cognitive_velocity = self.personal_best_position - self.position
#         # vektor od trenutne do globalne najbolje pozicije
#         social_velocity = Particle.swarm_best_position - self.position
            
#         r_p = np.random.random(len(cognitive_velocity))
#         r_s = np.random.random(len(social_velocity))
            
#         self.velocity = (self.c_i * self.velocity 
#                          + self.c_p * r_p * cognitive_velocity 
#                          + self.c_s * r_s * social_velocity)     

In [162]:
class Particle:
    swarm_best_position = None
    swarm_best_value = None
    
    def __init__(self, bounds, f, c_i, c_p, c_s):
        self.lower_bounds = bounds[:,0]
        self.upper_bounds = bounds[:,1]
        
        self.f = f
    
        self.c_i = c_i
        self.c_p = c_p
        self.c_s = c_s
        
        self.position = np.random.uniform(self.lower_bounds, self.upper_bounds, len(bounds))
        self.velocity = np.random.uniform(-1, 1, len(bounds))
        
        self.best_position = self.position
        self.value = f(self.position)
        self.personal_best_value = self.value
        
        if Particle.swarm_best_value is None or self.personal_best_value < Particle.swarm_best_value:
            Particle.swarm_best_position = self.best_position.copy()
            Particle.swarm_best_value = self.personal_best_value
            
    def update_position(self):
        self.position = np.clip(self.position + self.velocity,
                               self.lower_bounds,
                               self.upper_bounds)
        self.value = self.f(self.position)
        
        if self.value < self.personal_best_value:
            self.personal_best_value = self.value
            self.best_position = self.position.copy()
            
            if self.value < Particle.swarm_best_value:
                Particle.swarm_best_value = self.value
                
    
    def update_velocity(self):
        cognitive_velocity = self.best_position - self.position
        social_velocity = Particle.swarm_best_position - self.position
        
        r_p = np.random.random(len(cognitive_velocity))
        r_s = np.random.random(len(social_velocity))
        
        self.velocity = (self.velocity*self.c_i 
                        + cognitive_velocity*self.c_p*r_p
                        + social_velocity*self.c_s*r_s
                        )

In [132]:
lower_bounds = bounds[:, 0]
upper_bounds = bounds[:, 1]
        
position = np.random.uniform(lower_bounds, upper_bounds, len(bounds))
position

array([ 2.53267712, -3.00433635])

In [78]:
np.random.uniform(-1,1, len(bounds))

array([0.84310307, 0.03628591])

In [158]:
def pso(swarm_size, num_iters):
    swarm = [Particle(bounds, f=rastrigin, c_i=0.5, c_p=1, c_s=1) for _ in range(swarm_size)]
    
    for i in range(num_iters):
        for p in swarm:
            p.update_velocity()
            p.update_position()
    return Particle.swarm_best_position, Particle.swarm_best_value

In [161]:
pso(20, 100)

NameError: name 'f' is not defined